### PR TITLE
Feature/gb working

### PR DESCRIPTION
**Pull request by gbaren**
Tested on a rig

### CODE REVIEW

**Comment by dimichelec** [comment]
canary.h:
* readbit could be more efficient by removing a bit shift. Also, reg var should be protected with parens to not do something unexpected if a formula were used instead of a declared object:
  #define readbit(reg,bit) (((reg) >> (bit)) & 1)

* WDT_TIMEOUTs should be enclosed by parens to not do something unexpected if included in a formula (i.e., "WDT_TIMEOUT_128MS * 2" ==> "bitval(WDP1) | bitval(WDP0) * 2", which might only multiply the second bitval instead of the whole result).

main.cpp:

* don't need is_led_changed() function any more.
* fix "#ifdef SIM" block indent in idletime_input() to match other cases.
* setup_wdtcr "volatile unsigned" comments should be removed. obsolete.
* this could be made better on the battery if we don't reset wdt_counter in the WDT ISR. Instead, we can count and check "if (wdt_counter > configured_delay)" in the WDT ISR. If it is, check for an hd_led change there and reset_mobo if we haven't had one, otherwise, reset PCINT state and WDT counter and try again. This way would only check PCINT every configured_delay time instead of every WDT.

**Review by dimichelec — COMMENTED** [review]
canary.h:

readbit could be more efficient by removing a bit shift. Also, reg var should be protected with parens to not do something unexpected if a formula were used instead of a declared object:
#define readbit(reg,bit) (((reg) >> (bit)) & 1)

WDT_TIMEOUTs should be enclosed by parens to not do something unexpected if included in a formula (i.e., "WDT_TIMEOUT_128MS * 2" ==> "bitval(WDP1) | bitval(WDP0) * 2", which might only multiply the second bitval instead of the whole result).

main.cpp:

don't need is_led_changed() function any more.
fix "#ifdef SIM" block indent in idletime_input() to match other cases.
setup_wdtcr "volatile unsigned" comments should be removed. obsolete.
this could be made better on the battery if we don't reset wdt_counter in the WDT ISR. Instead, we can count and check "if (wdt_counter > configured_delay)" in the WDT ISR. If it is, check for an hd_led change there and reset_mobo if we haven't had one, otherwise, reset PCINT state and WDT counter and try again. This way would only check PCINT every configured_delay time instead of every WDT.

**Comment by gbaren** [comment]
I played around with allowing the PCINT only once per configured_delay. It doesn’t work very well. The delay can be as much as double the configured_delay. I think checking it once per WDT cycle should be good enough.

**Comment by dimichelec** [comment]
? It should extend the delay less than if checked every WDT—WDTs happen
every 8sec which would be 8 WDTs for a 1min config delay. Checking the PC
once per WDT means we are servicing PCINT 8 times vs once if we check it
once per config delay.

**Comment by gbaren** [comment]
If the final LED flash happens close to the beginning of the configured_delay cycle, the reset won’t occur until the end of the next cycle, making the delay almost double the configured delay.

**Comment by dimichelec** [comment]
True but it could cost a reduced battery life by something like 1/8. I’ll
break-out the oscilloscope when I’m back to get an accurate battery life
estimate to see if it matters.

**Comment by gbaren** [comment]
What you say makes a lot of sense. Gave it a good faith effort without reservation.

 

The problem I had in testing was the erratic timeout. It doesn’t matter much at lower values, but when you set it for 20 minutes and it turns it into 40, that could be a problem. 

 

By the way, I found competition. A board that plugs into the internal USB header on the motherboard and is hard-coded for 5 minutes. By a company in Minsk, Belarus. Costs $15 with shipping. Ordered one to check it out.

 



 

https://www.tindie.com/products/easySensors/mining-pc-watchdog-/

**Comment by dimichelec** [comment]
The one from Minsk looks like the same concept. Nice design. Some
 advantages we have are using the power switch instead of the reset button,
having battery power over usb which has cases where the mobo will turn it
off while still operating, not taking up a usb port when you might want to
use them all for other things, having more mounting options without needing
an uncommon extension cable, configurable timing, and an on/off switch. Our
disadvantages are not as compact a design, their leds might be useful, and
they will probably wind-up being cheaper.

**Pull request closed without merging**
